/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample1_JNIHelloWorld */

#ifndef _Included_sample1_JNIHelloWorld
#define _Included_sample1_JNIHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample1_JNIHelloWorld
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample1_JNIHelloWorld_printHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
