/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample2_JNISampleApp */

#ifndef _Included_sample2_JNISampleApp
#define _Included_sample2_JNISampleApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample2_JNISampleApp
 * Method:    print
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_sample2_JNISampleApp_print
  (JNIEnv *, jclass, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
