package sample5.my_code; 

import java.beans.*;

/* This source file is automatically generated by PropertyAnnotationProcessor. */

public class MyBeanWithProperties implements java.io.Serializable {

   private PropertyChangeSupport pcs = new PropertyChangeSupport(this);

   public void addPropertychangeListener(PropertyChangeListener l) {
       pcs.addPropertyChangeListener(l);
   }
   public void removePropertychangeListener(PropertyChangeListener l) {
       pcs.removePropertyChangeListener(l);
   }

   private java.lang.String stringValue;

   public synchronized void setStringValue(java.lang.String newValue) {
       java.lang.String oldValue = stringValue;
       stringValue =  newValue;
       pcs.firePropertyChange("stringValue", oldValue, newValue); 
   }
   public synchronized java.lang.String getStringValue() {
       return stringValue; 
   }

   private float floatValue;

   public synchronized void setFloatValue(float newValue) {
       float oldValue = floatValue;
       floatValue =  newValue;
       pcs.firePropertyChange("floatValue", oldValue, newValue); 
   }
   public synchronized float getFloatValue() {
       return floatValue; 
   }

   private java.lang.Object objectValue;

   public synchronized void setObjectValue(java.lang.Object newValue) {
       java.lang.Object oldValue = objectValue;
       objectValue =  newValue;
       pcs.firePropertyChange("objectValue", oldValue, newValue); 
   }
   public synchronized java.lang.Object getObjectValue() {
       return objectValue; 
   }

}
